/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ArtistRouteImport } from './routes/artist'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtistIndexRouteImport } from './routes/artist.index'
import { Route as ArtistSlugRouteImport } from './routes/artist.$slug'

const ArtistRoute = ArtistRouteImport.update({
  id: '/artist',
  path: '/artist',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistIndexRoute = ArtistIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtistRoute,
} as any)
const ArtistSlugRoute = ArtistSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArtistRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artist': typeof ArtistRouteWithChildren
  '/artist/$slug': typeof ArtistSlugRoute
  '/artist/': typeof ArtistIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artist/$slug': typeof ArtistSlugRoute
  '/artist': typeof ArtistIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artist': typeof ArtistRouteWithChildren
  '/artist/$slug': typeof ArtistSlugRoute
  '/artist/': typeof ArtistIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/artist' | '/artist/$slug' | '/artist/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/artist/$slug' | '/artist'
  id: '__root__' | '/' | '/artist' | '/artist/$slug' | '/artist/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtistRoute: typeof ArtistRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/artist': {
      id: '/artist'
      path: '/artist'
      fullPath: '/artist'
      preLoaderRoute: typeof ArtistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/': {
      id: '/artist/'
      path: '/'
      fullPath: '/artist/'
      preLoaderRoute: typeof ArtistIndexRouteImport
      parentRoute: typeof ArtistRoute
    }
    '/artist/$slug': {
      id: '/artist/$slug'
      path: '/$slug'
      fullPath: '/artist/$slug'
      preLoaderRoute: typeof ArtistSlugRouteImport
      parentRoute: typeof ArtistRoute
    }
  }
}

interface ArtistRouteChildren {
  ArtistSlugRoute: typeof ArtistSlugRoute
  ArtistIndexRoute: typeof ArtistIndexRoute
}

const ArtistRouteChildren: ArtistRouteChildren = {
  ArtistSlugRoute: ArtistSlugRoute,
  ArtistIndexRoute: ArtistIndexRoute,
}

const ArtistRouteWithChildren =
  ArtistRoute._addFileChildren(ArtistRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtistRoute: ArtistRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
