/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ArtistRouteImport } from "./routes/artist";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ArtistIndexRouteImport } from "./routes/artist.index";
import { Route as ArtistSlugRouteImport } from "./routes/artist.$slug";

const ArtistRoute = ArtistRouteImport.update({
  id: "/artist",
  path: "/artist",
  getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
});
const ArtistIndexRoute = ArtistIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ArtistRoute,
});
const ArtistSlugRoute = ArtistSlugRouteImport.update({
  id: "/$slug",
  path: "/$slug",
  getParentRoute: () => ArtistRoute,
});

const ArtistRouteChildren = {
  ArtistSlugRoute: ArtistSlugRoute,
  ArtistIndexRoute: ArtistIndexRoute,
};

const ArtistRouteWithChildren = ArtistRoute._addFileChildren(ArtistRouteChildren);

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtistRoute: ArtistRouteWithChildren,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes();
